"""
DEPRECATED: Use action_config.py instead
This file is kept for backwards compatibility during migration
"""

# Import all constants from the new centralized config
from .action_config import (
    WORK_BASE_COOLDOWN,
    PATROL_COOLDOWN,
    FARM_COOLDOWN,
    SABOTAGE_COOLDOWN,
    SCOUT_COOLDOWN,
    TRAINING_COOLDOWN,
    CRAFTING_BASE_COOLDOWN,
    VAULT_HEIST_COOLDOWN,
    VAULT_HEIST_COOLDOWN_HOURS,
    MIN_INTELLIGENCE_REQUIRED,
    HEIST_COST,
    HEIST_PERCENT,
    MIN_HEIST_AMOUNT,
    BASE_HEIST_DETECTION,
    VAULT_LEVEL_BONUS,
    INTELLIGENCE_REDUCTION,
    PATROL_BONUS,
    HEIST_REP_LOSS,
    HEIST_BAN,
    FARM_GOLD_REWARD,
    SCOUT_GOLD_REWARD,
    PATROL_GOLD_REWARD,
    PATROL_REPUTATION_REWARD,
    PATROL_DURATION_MINUTES
)

