import Foundation

// MARK: - Contract System
// EVE Online-inspired contracts for kingdom building

struct Contract: Identifiable, Codable, Hashable {
    let id: String  // String to match backend contract endpoints
    let kingdomId: String
    let kingdomName: String
    
    // What's being built
    let buildingType: String
    let buildingLevel: Int
    
    // Time requirements (scaled by population and building level)
    let basePopulation: Int // Population when contract was created
    let baseHoursRequired: Double // Base time with ideal workers
    var workStartedAt: Date? // When first worker accepted
    
    // Action requirements (new system)
    let totalActionsRequired: Int // Total actions needed to complete
    var actionsCompleted: Int // Current action progress
    var actionContributions: [String: Int] // user_id: action_count
    
    // Costs & Rewards
    let constructionCost: Int? // What ruler paid upfront to START building (kingdom contracts only)
    let rewardPool: Int // Total gold to distribute to workers
    let actionReward: Int // Gold per action (ruler-set)
    
    // Status
    let createdBy: Int // Ruler's player ID (PostgreSQL auto-generated)
    let createdAt: Date
    var completedAt: Date?
    var status: ContractStatus
    
    enum ContractStatus: String, Codable {
        case open       // Posted, waiting for workers
        case inProgress // Workers signed up, timer running
        case completed  // Finished, building upgraded
        case cancelled  // Cancelled by ruler
    }
    
    // MARK: - Computed Properties
    
    var contributorCount: Int {
        actionContributions.count
    }
    
    var isComplete: Bool {
        status == .completed
    }
    
    /// Time to complete based on number of contributors
    /// More contributors = faster completion (parallel work)
    var hoursToComplete: Double {
        let idealContributors = 3.0  // Ideal team size
        let contributorMultiplier = idealContributors / max(Double(contributorCount), 1.0)
        return baseHoursRequired * contributorMultiplier
    }
    
    /// Progress percentage (0.0 to 1.0)
    var progress: Double {
        if status == .completed {
            return 1.0
        }
        
        // Use action-based progress
        if totalActionsRequired > 0 {
            return Double(actionsCompleted) / Double(totalActionsRequired)
        }
        
        // Fallback to time-based for legacy contracts
        guard let startTime = workStartedAt, status == .inProgress else {
            return 0.0
        }
        
        let elapsed = Date().timeIntervalSince(startTime) / 3600.0 // hours
        let progress = elapsed / hoursToComplete
        return min(progress, 1.0)
    }
    
    /// Time remaining in hours
    var hoursRemaining: Double? {
        guard let startTime = workStartedAt, status == .inProgress else {
            return nil
        }
        
        let elapsed = Date().timeIntervalSince(startTime) / 3600.0
        let remaining = hoursToComplete - elapsed
        return max(remaining, 0.0)
    }
    
    /// Check if contract is ready to complete
    var isReadyToComplete: Bool {
        // Check action-based completion
        if totalActionsRequired > 0 {
            return actionsCompleted >= totalActionsRequired
        }
        
        // Fallback to time-based for legacy contracts
        guard let remaining = hoursRemaining else { return false }
        return remaining <= 0.0
    }
    
    /// Reward per contributor (proportional split)
    var rewardPerContributor: Int {
        guard contributorCount > 0 else { return 0 }
        return rewardPool / contributorCount
    }
    
    // MARK: - Mutations
    
    /// Mark contract as completed
    mutating func complete() {
        status = .completed
        completedAt = Date()
    }
    
    // MARK: - Factory Method
    
    /// Create a new contract with time scaled by population and building level
    /// Note: In production, ID is auto-generated by the backend database
    static func create(
        id: String = "1",  // For sample data only - backend generates this
        kingdomId: String,
        kingdomName: String,
        buildingType: String,
        buildingLevel: Int,
        population: Int,
        actionReward: Int,  // Gold per action
        createdBy: Int
    ) -> Contract {
        // Scale time required based on building level and population
        let baseHours = 2.0 * pow(2.0, Double(buildingLevel - 1))
        let populationMultiplier = 1.0 + (Double(population) / 30.0)
        let totalHours = baseHours * populationMultiplier
        
        // Calculate action requirements: 100 * 2^(level-1) * (1 + population/30)
        let baseActions = 100.0 * pow(2.0, Double(buildingLevel - 1))
        let populationActionMultiplier = 1.0 + (Double(population) / 30.0)
        let totalActions = Int(baseActions * populationActionMultiplier)
        
        // Calculate construction cost: 1000 * 2^(level-1) * (1 + population/50)
        // Only for kingdom building contracts
        let baseCost = 1000.0 * pow(2.0, Double(buildingLevel - 1))
        let populationCostMultiplier = 1.0 + (Double(population) / 50.0)
        let constructionCostValue = Int(baseCost * populationCostMultiplier)
        
        // Calculate upfront cost and reward pool from action_reward
        let upfrontCost = totalActions * actionReward
        
        return Contract(
            id: id,
            kingdomId: kingdomId,
            kingdomName: kingdomName,
            buildingType: buildingType,
            buildingLevel: buildingLevel,
            basePopulation: population,
            baseHoursRequired: totalHours,
            workStartedAt: nil,
            totalActionsRequired: totalActions,
            actionsCompleted: 0,
            actionContributions: [:],
            constructionCost: upfrontCost,
            rewardPool: upfrontCost,
            actionReward: actionReward,
            createdBy: createdBy,
            createdAt: Date(),
            completedAt: nil,
            status: .open
        )
    }
}


